name: GitHub Actions Demo

on: 
  push:
    branches: main
    paths-ignore: [.github/**]
  pull_request:
    branches: main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environments: 
      description: 'Environment to deploy to'
      type: environment
      required: true

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - run: |
                echo "The job was triggered by event ${{github.event_name}}"
                echo "The name of your branch is ${{github.ref}} and your repository is "
        - name: Checkout repository
          uses: actions/Checkout@v4.2.2

        - name: List files in repository
          run: |
                echo "The repository ${{github.repository}} contains following files"
                tree

  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: build
    environment: Test
    steps:
      -run: |
          echo "/ Testing..."

  load-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: build
    environment: Load-Test
    steps:
      -run: |
       echo "/ Testing..."
       sleep 15

    production:
      runs-on: ubuntu-latest
      if: github.event.inputs.environment == 'Production'
      needs: [test, load-test]
      environment: 
        url: https://writeabout.net
        name: Production
      steps:
        -run: |
         echo "/ Deploying..."
         sleep 10
          -run: |
         echo "/ Step 1..."
         sleep 10
           -run: |
         echo "/ Step 2..."
         sleep 10
           -run: |
         echo "/ Step 3..."
         sleep 10
           -run: |
         echo "/ Step 4..."
         sleep 10
         
       
      
    
      
                
        
                
        
    
